BZRForumMedia.Server/Controllers/KorisnikDokumentacijaController.cs
namespace BZRForumMedia.Server.Controllers
{
    using BZRForumMedia.Server.Data;
    using BZRForumMedia.Server.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class KorisnikDokumentacijaController : Controller
    {
        private readonly ApplicationDbContext _context;
        public KorisnikDokumentacijaController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListaDokumenata(int id)
        {
            List<Dokumentacija> dokumenti = await _context.Dokumentacije
                .Where(d => d.IdTipa == id)
                .Select(d => new Dokumentacija { Id = d.Id, Naslov = d.Naslov, DatumObjavljivanja = d.DatumObjavljivanja })
                .OrderByDescending(d => d.Id)
                .ToListAsync();
            return View(dokumenti);
        }

        [Authorize(Roles = "Super korisnik, Korisnik")]
        public async Task<IActionResult> JedanDokument(int id)
        {
            Dokumentacija dokument = await _context.Dokumentacije.FindAsync(id);
            return View(dokument);
        }
    }
}

BZRForumMedia.Server/Views/KorisnikDokumentacija/JedanDokument.cshtml
@model BZRForumMedia.Server.Models.Dokumentacija;
@{
}
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">@Model.Naslov</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna</a></li>
                                <li class="active">Dokumentacija</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<!-- section -->
<div class="section padding_layout_1 it_service_policy">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="full">
                            <h2 style="text-align: center;">@Model.Naslov</h2>
                            
                            <br>
                            <br>
                            @Html.Raw(@Model.Tekst)


                            <div class="full margin_bottom_30">
                                <div class="accordion border_circle">
                                    <div class="bs-example">
                                        <div class="panel-group" id="accordion">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <p class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><i class="fa fa-bar-chart" aria-hidden="true"></i> Atributi dokumenta <i class="fa fa-angle-down"></i></a> </p>
                                                </div>
                                                <div id="collapseOne" class="panel-collapse collapse in">
                                                    <div class="panel-body">
                                                        <p>
                                                            Datum objavljivanja: @(Model.DatumObjavljivanja.HasValue?@Model.DatumObjavljivanja.Value.ToString("dd/MM/yyyy") : "Podatak trenutno ne postoji") <br>
                                                            PDF dokument: <a href="@Model.PdfPutanja">PDF</a> <br>



                                                        </p>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end section -->

BZRForumMedia.Server/Views/KorisnikDokumentacija/ListaDokumenata.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<BZRForumMedia.Server.Models.Dokumentacija>
@{
}

<!-- inner page banner -->
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">Dokumentacija</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna strana</a></li>
                                <li class="active">Dokumentacija</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<div class="section padding_layout_1 Shopping_cart_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="product-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Naslov</th>
                                <th>Datum objavljivanja</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var dokument in Model)
                            {
                                <tr>
                                    <td class="col-sm-8 col-md-6">
                                        <div class="media">
                                            <a class="thumbnail pull-left" href="#"> </a>
                                            <div class="media-body">
                                                <h4 class="media-heading"><a href="#">@dokument.Naslov</a></h4>
                                                <span>Status: </span><span class="text-danger">Važeći</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-sm-1 col-md-1 text-center"><p class="price_table">@(dokument.DatumObjavljivanja.HasValue? dokument.DatumObjavljivanja.Value.ToString("dd/MM/yyyy") : "Podatak ne postoji")</p></td>

                                    @if (SignInManager.IsSignedIn(User))
                                    {


                                        <td class="col-sm-1 col-md-1">
                                            <a type="button" class="bt_main" asp-action="JedanDokument" asp-controller="KorisnikDokumentacija" asp-route-id="@dokument.Id">
                                                <i class="fa fa-unlock"></i> Prikaz
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="col-sm-1 col-md-1"><button type="button" class="bt_main"><i class="fa fa-lock"></i> Zaključan</button></td>
                                    }

                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>