BZRForumMedia.Server/Controllers/KorisnikClanakController.cs
namespace BZRForumMedia.Server.Controllers
{
    using BZRForumMedia.Server.Data;
    using BZRForumMedia.Server.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class KorisnikClanakController : Controller
    {
        private readonly ApplicationDbContext _context;
        public KorisnikClanakController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListaClanaka()
        {
            List<Clanak> clanci = await _context.Clanci
                .Select(c => new Clanak { Id = c.Id, Naslov = c.Naslov, Autor = c.Autor })
                .OrderByDescending(c => c.Id)
                .ToListAsync();
            return View(clanci);
        }
        [Authorize(Roles = "Super korisnik, Korisnik")]
        public async Task<IActionResult> JedanClanak(int id)
        {
            Clanak clanak = await _context.Clanci.FindAsync(id);
            return View(clanak);
        }
    }
}

BZRForumMedia.Server/Views/KorisnikClanak/JedanClanak.cshtml
@model BZRForumMedia.Server.Models.Clanak;
@{
}
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">Članak</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna</a></li>
                                <li class="active">Članci</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<!-- section -->
<div class="section padding_layout_1 it_service_policy">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="full">
                            <h2 style="text-align: center;">@Model.Naslov</h2>

                            <br>
                            <br>
                            @Html.Raw(@Model.TekstClanka)


                            <div class="full margin_bottom_30">
                                <div class="accordion border_circle">
                                    <div class="bs-example">
                                        <div class="panel-group" id="accordion">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <p class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><i class="fa fa-bar-chart" aria-hidden="true"></i> Atributi članka <i class="fa fa-angle-down"></i></a> </p>
                                                </div>
                                                <div id="collapseOne" class="panel-collapse collapse in">
                                                    <div class="panel-body">
                                                        <p>
                                                            Datum objavljivanja: @Model.DatumObjavljivanja.ToString("dd/MM/yyyy") <br>
                                                            Autor: @Model.Autor<br />
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end section -->

BZRForumMedia.Server/Views/KorisnikClanak/ListaClanaka.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<BZRForumMedia.Server.Models.Clanak>
@{
}

<!-- inner page banner -->
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">Članci</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna strana</a></li>
                                <li class="active">Članci</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<div class="section padding_layout_1 Shopping_cart_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="product-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Naslov</th>
                                <th>Autor</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var clanak in Model)
                            {
                                <tr>
                                    <td class="col-sm-8 col-md-6">
                                        <div class="media">
                                            <a class="thumbnail pull-left" href="#"> </a>
                                            <div class="media-body">
                                                <h4 class="media-heading"><a href="#">@clanak.Naslov</a></h4>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-sm-1 col-md-1 text-center"><p class="price_table">@clanak.Autor</p></td>

                                    @if (SignInManager.IsSignedIn(User))
                                    {


                                        <td class="col-sm-1 col-md-1">
                                            <a type="button" class="bt_main" asp-action="JedanClanak" asp-controller="KorisnikClanak" asp-route-id="@clanak.Id">
                                                <i class="fa fa-unlock"></i> Prikaz
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="col-sm-1 col-md-1"><button type="button" class="bt_main"><i class="fa fa-lock"></i> Zaključan</button></td>
                                    }

                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>