BZRForumMedia.Server/Controllers/KorisnikPropisController.cs
namespace BZRForumMedia.Server.Controllers
{
    using BZRForumMedia.Server.Data;
    using BZRForumMedia.Server.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class KorisnikPropisController : Controller
    {
        private readonly ApplicationDbContext _context;
        public KorisnikPropisController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListaPropisa(int id)
        {
            List<Propis> propisi = await _context.Propisi
                .Where(p => p.IdVrstaPropis == id)
                .Select(p => new Propis { Id = p.Id, Naslov = p.Naslov, GlasiloIDatum = p.GlasiloIDatum, IdVrstaPropis = p.IdVrstaPropis, DatumStupanjaNaSnaguPropisa = p.DatumStupanjaNaSnaguPropisa })
                .ToListAsync();
            return View(propisi);
        }

        [Authorize(Roles = "Korisnik, Super korisnik")]
        public async Task<IActionResult> JedanPropis(int id)
        {
            var propis = await _context.Propisi.FindAsync(id);
            return View(propis);
        }
    }
}

BZRForumMedia.Server/Views/KorisnikPropis/JedanPropis.cshtml
@model BZRForumMedia.Server.Models.Propis;
@{
}
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">Propisi</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna</a></li>
                                <li class="active">Propisi</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<!-- section -->
<div class="section padding_layout_1 it_service_policy">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="full">
                            <h2 style="text-align: center;">@Model.Naslov</h2>
                            <p class="large">@Model.GlasiloIDatum</p>
                            <br>
                            <br>
                           @Html.Raw(@Model.TekstPropisa)
                    

                    <div class="full margin_bottom_30">
                        <div class="accordion border_circle">
                            <div class="bs-example">
                                <div class="panel-group" id="accordion">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <p class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><i class="fa fa-bar-chart" aria-hidden="true"></i> Atribut propisa <i class="fa fa-angle-down"></i></a> </p>
                                        </div>
                                        <div id="collapseOne" class="panel-collapse collapse in">
                                            <div class="panel-body">
                                                <p>
                                                    Glasilo i datum: @Model.GlasiloIDatum <br>
                                                    Datum objavljivanja osnovnog teksta: @(Model.DatumObjavljivanjaOsnovnogTeksta.HasValue?@Model.DatumObjavljivanjaOsnovnogTeksta.Value.ToString("dd/MM/yyyy") : "Datum trenutno ne postoji")<br>
                                                    Datum objavljivanja Verzije: @(Model.DatumObjavljivanjeVerzije.HasValue?@Model.DatumObjavljivanjeVerzije.Value.ToString("dd/MM/yyyy") : "Datum trenutno ne postoji") <br>
                                                    Datum početka primene: @( Model.DatumPocetkaPrimene.HasValue?@Model.DatumPocetkaPrimene.Value.ToString("dd/MM/yyyy"): "Datum trenutno ne postoji")<br>
                                                    Datum prestanka važenja: @(Model.DatumPrestankaVazenjaPropisa.HasValue?@Model.DatumPrestankaVazenjaPropisa.Value.ToString("dd/MM/yyyy") : "Datum trenutno ne postoji") <br>
                                                    Datum prestanka važenja pravnog prethodnika: @(Model.DatumPrestankaVazenjaPravnogPrethodnika.HasValue? @Model.DatumPrestankaVazenjaPravnogPrethodnika.Value.ToString("dd/MM/yyyy") : "Datum trenutno ne postoji") <br>

                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
        </div>
    </div>
<!-- end section -->

BZRForumMedia.Server/Views/KorisnikPropis/ListaPropisa.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<BZRForumMedia.Server.Models.Propis>
@{
}
<!-- inner page banner -->
<div id="inner_banner" class="section inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="title-holder">
                        <div class="title-holder-cell text-left">
                            <h1 class="page-title">Propisi</h1>
                            <ol class="breadcrumb">
                                <li><a asp-controller="Home" asp-action="Index">Početna strana</a></li>
                                <li class="active">Propisi</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end inner page banner -->
<div class="section padding_layout_1 Shopping_cart_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="product-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Naslov</th>
                                <th>Glasilo i datum</th>
                                <th>Datum stupanja na snagu</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var propis in Model)
                            {
                                <tr>
                                    <td class="col-sm-8 col-md-6">
                                        <div class="media">
                                            <a class="thumbnail pull-left" href="#"> </a>
                                            <div class="media-body">
                                                <h4 class="media-heading"><a href="#">@propis.Naslov</a></h4>
                                                <span>Status: </span><span class="text-danger">Važeći</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-sm-1 col-md-1 text-center"><p class="price_table"  title="@propis.GlasiloIDatum"style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; width: 100px;">@propis.GlasiloIDatum</p></td>

                                    <td class="col-sm-1 col-md-1 text-center" ><p class="price_table" >@(propis.DatumStupanjaNaSnaguPropisa.HasValue? propis.DatumStupanjaNaSnaguPropisa.Value.ToString("dd/MM/yyyy") : "Zapis ne postoji")</p></td>
                                    @if (SignInManager.IsSignedIn(User))
                                    {


                                        <td class="col-sm-1 col-md-1">
                                            <a type="button" class="bt_main" asp-action="JedanPropis" asp-controller="KorisnikPropis" asp-route-id="@propis.Id">
                                                <i class="fa fa-unlock"></i> Prikaz
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="col-sm-1 col-md-1"><button type="button" class="bt_main"><i class="fa fa-lock"></i> Zaključan</button></td>
                                    }

                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>