BZRForumMedia.Server/Controllers/AdminPitanjaIOdgovoriController.cs
namespace BZRForumMedia.Server.Controllers
{
    using BZRForumMedia.Server.Data;
    using BZRForumMedia.Server.Models;
    using BZRForumMedia.Server.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    [Authorize(Roles = "Administrator")]
    public class AdminPitanjaIOdgovoriController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AdminPitanjaIOdgovoriController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListaPitanja()
        {
            List<PitanjaIOdgovori> pitanja = await _context.PitanjaIOdgovori
                .Select(p => new PitanjaIOdgovori { Id = p.Id, Pitanje = p.Pitanje})
                .OrderByDescending(p => p.Id).ToListAsync();
            return View(pitanja);
        }

        [HttpGet]
        public IActionResult CreatePitanja()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePitanja(PitanjaIOdgovoriViewModel model)
        {
            if (ModelState.IsValid)
            {
                PitanjaIOdgovori pitanje = new PitanjaIOdgovori
                {
                    Naslov = model.Naslov,
                    Pitanje = model.Pitanje,
                    Odgovor = model.Odgovor
                };
                await _context.PitanjaIOdgovori.AddAsync(pitanje);
                await _context.SaveChangesAsync();
                ViewBag.Msg = "Uspešno je dodato";
                return View();
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditPitanja(int id)
        {
            PitanjaIOdgovori pitanje = await _context.PitanjaIOdgovori.FindAsync(id);
            if(pitanje == null)
            {
                return View("Error");
            }
            PitanjaIOdgovoriViewModel model = new PitanjaIOdgovoriViewModel
            {
                Naslov = pitanje.Naslov,
                Pitanje = pitanje.Pitanje,
                Odgovor = pitanje.Odgovor
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPitanja(PitanjaIOdgovoriViewModel model, int id)
        {
            if (ModelState.IsValid)
            {
                PitanjaIOdgovori pitanje = await _context.PitanjaIOdgovori.FindAsync(id);
                pitanje.Naslov = model.Naslov;
                pitanje.Pitanje = model.Pitanje;
                pitanje.Odgovor = model.Odgovor;
                _context.PitanjaIOdgovori.Update(pitanje);
                await _context.SaveChangesAsync();
                return RedirectToAction("ListaPitanja");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsPitanja(int id)
        {
            PitanjaIOdgovori pitanje = await _context.PitanjaIOdgovori.FindAsync(id);
            if(pitanje == null)
            {
                return View("Error");
            }
            ViewBag.Id = id;
            PitanjaIOdgovoriViewModel model = new PitanjaIOdgovoriViewModel
            {
                Naslov = pitanje.Naslov,
                Pitanje = pitanje.Pitanje,
                Odgovor = pitanje.Odgovor
            };
            return View(model);
        }

        public async Task<IActionResult> DeletePitanja(int id)
        {
            PitanjaIOdgovori pitanje = await _context.PitanjaIOdgovori.FindAsync(id);
            if(pitanje == null)
            {
                return View("Error");
            }
            _context.PitanjaIOdgovori.Remove(pitanje);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListaPitanja");
        }

    }
}

BZRForumMedia.Server/Views/AdminPitanjaIOdgovori/CreatePitanja.cshtml
@model BZRForumMedia.Server.ViewModels.PitanjaIOdgovoriViewModel

@{
    ViewData["Title"] = "Kreiraj pitanje";
}
<div class="container">
    <h1>Kreiraj pitanja</h1>

    <h4>Popunite sva polja</h4>
    @if (@ViewBag.Msg != null)
    {
        <h4 class="text-success">@ViewBag.Msg</h4>
    }
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreatePitanja">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Naslov" class="control-label"></label>
                    <input asp-for="Naslov" class="form-control" />
                    <span asp-validation-for="Naslov" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Pitanje" class="control-label"></label>
                    <input asp-for="Pitanje" class="form-control" />
                    <span asp-validation-for="Pitanje" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Odgovor" class="control-label"></label>
                    <input asp-for="Odgovor" class="form-control" />
                    <span asp-validation-for="Odgovor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Kreiraj" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="ListaPitanja">Nazad na listu</a>
    </div>

</div>

BZRForumMedia.Server/Views/AdminPitanjaIOdgovori/DetailsPitanja.cshtml
@model BZRForumMedia.Server.ViewModels.PitanjaIOdgovoriViewModel

@{
    ViewData["Title"] = "Detalji o pitanju";
    int idPitanja = ViewBag.Id;
}
<div class="container">
    <h1>Detalji o pitanju</h1>

    <div>
        <h4>sve informacije</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Naslov)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Naslov)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Pitanje)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Pitanje)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Odgovor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Odgovor)
            </dd>
        </dl>
    </div>
    <div>
        @Html.ActionLink("Izmeni", "EditPitanja", new { id = idPitanja }) |
        <a asp-action="ListaPitanja">Nazad na listu</a>
    </div>
</div>

BZRForumMedia.Server/Views/AdminPitanjaIOdgovori/EditPitanja.cshtml
@model BZRForumMedia.Server.ViewModels.PitanjaIOdgovoriViewModel

@{
    ViewData["Title"] = "Izmeni pitanje";
}
<div class="container">
    <h1>Izmeni pitanje</h1>

    <h4>Popuni polja</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="EditPitanja">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Naslov" class="control-label"></label>
                    <input asp-for="Naslov" class="form-control" />
                    <span asp-validation-for="Naslov" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Pitanje" class="control-label"></label>
                    <input asp-for="Pitanje" class="form-control" />
                    <span asp-validation-for="Pitanje" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Odgovor" class="control-label"></label>
                    <input asp-for="Odgovor" class="form-control" />
                    <span asp-validation-for="Odgovor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Sačuvaj" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="ListaPitanja">Nazad na listu</a>
    </div>

</div>

BZRForumMedia.Server/Views/AdminPitanjaIOdgovori/ListaPitanja.cshtml
@model IEnumerable<BZRForumMedia.Server.Models.PitanjaIOdgovori>

@{
    ViewData["Title"] = "Lista pitanja";
}
<div class="container">
    <h1>Lista pitanja</h1>

    <p>
        <a asp-action="CreatePitanja">Kreiraj novo pitanje</a>
    </p>
    <table class="table">
        <thead>
            <tr>


                <th>
                    @Html.DisplayNameFor(model => model.Pitanje)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>


                    <td>
                        @Html.DisplayFor(modelItem => item.Pitanje)
                    </td>

                    <td>
                        @Html.ActionLink("Izmeni", "EditPitanja", new { id = item.Id }) |
                        @Html.ActionLink("Detalji", "DetailsPitanja", new { id = item.Id }) |
                        <a asp-controller="AdminPitanjaIOdgovori" asp-action="DeletePitanja" asp-route-id="@item.Id" onclick="return confirm('jeste li sigurni da zelite da izbrisete @item.Pitanje')">Izbriši</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>